# This workflow will build an Arch Linux ISO file with the commit on it

name: Build Custom Arch ISO

on:
  push:
    branches:
      - master
      - main # In case we adopt this convention in the future
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'
  release:
    types:
      - created

jobs:
  build:
    runs-on: archlinux-latest
    #container:
      #image: archlinux/archlinux:latest
      #options: --privileged
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: pwd
      - run: find .
      - run: cat /etc/os-release
      - run: pacman-key --init
      - run: pacman --noconfirm -Sy archlinux-keyring git parted
      - run: git clone https://github.com/shivjeet1/auto-install.git
      - run: cd auto-install
      - run: bash arch.sh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Custom Arch Live ISO
          path: /tmp/archlive/out/*.iso
