# This workflow will build an Arch Linux ISO file with the commit on it

name: Build Custom Arch ISO

on:
  push:
    paths:
      - 'arch.sh'
    branches:
      - master
      - main # In case we adopt this convention in the future
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install required Packages in workflow 
        run: pacman -Sy --noconfirm grub xorriso dosfstools mtools base base-devel
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - run: bash arch.sh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Custom Arch Live ISO
          path: /tmp/archlive/out/*.iso
