# This workflow will build an Arch Linux ISO file with the commit on it

name: Build Custom Arch ISO

on:
  push:
    paths:
      - 'arch.sh'
    branches:
      - master
      - main # In case we adopt this convention in the future
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.editorconfig'
      - '**.gitignore'
      - '**.md'
      - 'LICENSE'
      - 'PKGBUILD'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install required Packages in workflow 
        run: pacman -Sy --noconfirm base base-devel linux grub xorriso dosfstools mtools
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Preparing a skeleton of ISO structure
        run: |
          # necessary files for xorriso
          mkdir -p customiso/{boot/grub, root, etc/systemd/system/getty@tty1.service.d}
          cp /boot/vmlinuz-linux customiso/boot/vmlinuz
          cp /boot/initramfs-linux.img customiso/initrd.img
          
          # copying arch.sh to customiso root directory
          cp arch.sh customiso/root/arch.sh
          cp config.json customiso/root/config.json
          chmod +x customiso/root/arch.sh

          # minimal GRUB for initial boot
          cat > customiso/boot/grub/grub.cfg <<EOF
          set default = 0
          set timeout = 3
          menuentry "Custom Arch auto-install" {
            linux /boot/vmlinuz
            initrd /boot/initrd.img
          }
          EOF

          # Auto login to TTY1 as root
          cat > customiso/etc/systemd/getty@tty1.service.d/override.conf << EOF
          [Service]
          ExecStart=
          ExecStart=~/usr/bin/agetty --autologin root --noclear %I \$TERM
          EOF

          # Auto-run arch.sh on login
          cat > customiso/root/.bash_profile << EOF
          #!/bin/sh
          /root/arch.sh
          EOF
          chmod +x customiso/root/.bash_profile

      - name: Build ISO using xorriso
        run: grub-mkrescue -o custom-arch.iso customiso

      - name: Upload ISO as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-arch-iso
          path: custom-arch.iso


